name: CI

on: [pull_request]

jobs:
  build:
    name: Test and lint project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn and test editor
        run: |
          echo Running CI test on the editor...
          npm install -g yarn
          cd anti-materiel-editor
          yarn install
          yarn ci

      - name: Install yarn and test app
        run: |
          echo Running CI test on the app...
          npm install -g yarn
          cd anti-materiel-app
          yarn install
          yarn test
        env:
          CI: true
