name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test and lint project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install yarn and test
      run: |
        npm install -g yarn
        cd anti-materiel-editor
        yarn install
        yarn ci
      env:
        CI: true
